/*
 * Copyright (C) 2021 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package android.content.om;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import android.os.Parcel;
import android.os.Parcelable;

/**
 * A key used to uniquely identify a Runtime Resource Overlay (RRO).
 * <!-- For applications -->
 *
 * <p>An overlay always belongs to a package and have a mandatory name associated with it. The name
 * helps uniquely identify a particular overlay within a package.
 *
 * <!-- For OverlayManagerService, it isn't public part and hidden by HTML comment. -->
 * <!--
 * <p>An overlay always belongs to a package and may optionally have a name associated with it. The
 * name helps uniquely identify a particular overlay within a package.
 * -->
 *
 * @see OverlayInfo#getOverlayIdentifier()
 */
public final class OverlayIdentifier implements Parcelable {
    /**
     * Creates an identifier from a package and unique name within the package.
     *
     * @param packageName the package containing or owning the overlay
     * @param overlayName the unique name of the overlay within the package
     * @hide
     */
    public OverlayIdentifier(@NonNull String packageName, @Nullable String overlayName) {
        throw new RuntimeException("STUB");
    }

    /**
     * Creates an identifier for an overlay without a name.
     *
     * @param packageName the package containing or owning the overlay
     * @hide
     */
    public OverlayIdentifier(@NonNull String packageName) {
        throw new RuntimeException("STUB");
    }

    /** @hide */
    @NonNull
    public static OverlayIdentifier fromString(@NonNull String text) {
        throw new RuntimeException("STUB");
    }

    // Code below generated by codegen v1.0.23.
    //
    // DO NOT MODIFY!
    // CHECKSTYLE:OFF Generated code
    //
    // To regenerate run:
    // $ codegen $ANDROID_BUILD_TOP/frameworks/base/core/java/android/content/om/OverlayIdentifier.java
    //
    // To exclude the generated code from IntelliJ auto-formatting enable (one-time):
    //   Settings > Editor > Code Style > Formatter Control
    //@formatter:off


    /**
     * Retrieves the package name containing or owning the overlay.
     *
     * @hide
     */
    public @Nullable String getPackageName() {
        throw new RuntimeException("STUB");
    }

    /**
     * Retrieves the unique name within the package of the overlay.
     *
     * @hide
     */
    public @Nullable String getOverlayName() {
        throw new RuntimeException("STUB");
    }

    @Override
    public int describeContents() {
        throw new RuntimeException("STUB");
    }

    @Override
    public void writeToParcel(@NonNull Parcel dest, int flags) {
        throw new RuntimeException("STUB");
    }

    private OverlayIdentifier(Parcel in) {
        throw new RuntimeException("STUB");
    }

    public static final Creator<OverlayIdentifier> CREATOR = new Creator<OverlayIdentifier>() {
        @Override
        public OverlayIdentifier createFromParcel(Parcel in) {
            throw new RuntimeException("STUB");
        }

        @Override
        public OverlayIdentifier[] newArray(int size) {
            throw new RuntimeException("STUB");
        }
    };
}
